CREATE DATABASE BANCOXYZ
USE BANCOXYZ


CREATE TABLE CLIENTE (
  idCLIENTE INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRES VARCHAR(100) NULL,
  APELLIDOS VARCHAR(100) NULL,
  DIRECCION VARCHAR(200) NULL,
  TELEFONO INTEGER UNSIGNED NULL,
  PRIMARY KEY(idCLIENTE)
);

CREATE TABLE SALDO (
  idSALDO INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  SALDO INTEGER UNSIGNED NULL,
  FECHAREGISTRO DATE NULL,
  PRIMARY KEY(idSALDO)
);

CREATE TABLE PAIS (
  idPAIS INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(150) NULL,
  PRIMARY KEY(idPAIS)
);

CREATE TABLE CIUDAD (
  IDCIUDAD INTEGER UNSIGNED NOT NULL,
  NOMBRE VARCHAR(150) NULL,
  DEPARTAMENTO VARCHAR(150) NULL,
  PAIS_idPAIS INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(IDCIUDAD),
  INDEX CIUDAD_FKIndex1(PAIS_idPAIS)
);

CREATE TABLE MOVIMIENTOS (
  idMOVIMIENTOS INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  SALDO_idSALDO INTEGER UNSIGNED NOT NULL,
  CUENTA_idCUENTA INTEGER UNSIGNED NOT NULL,
  VALOR INTEGER UNSIGNED NULL,
  FECHAREGISTRO DATE NULL,
  PRIMARY KEY(idMOVIMIENTOS),
  INDEX MOVIMIENTOS_FKIndex1(CUENTA_idCUENTA),
  INDEX MOVIMIENTOS_FKIndex2(SALDO_idSALDO)
);

CREATE TABLE CUENTA (
  idCUENTA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  CIUDAD_IDCIUDAD INTEGER UNSIGNED NOT NULL,
  CLIENTE_idCLIENTE INTEGER UNSIGNED NOT NULL,
  NUMERO INTEGER UNSIGNED NULL,
  PRIMARY KEY(idCUENTA),
  INDEX CUENTA_FKIndex1(CIUDAD_IDCIUDAD),
  INDEX CUENTA_FKIndex2(CLIENTE_idCLIENTE)
);